language: node_js
node_js:
  - "22"

services:
  - docker

before_install:
  - npm install -g @angular/cli

install:
  - npm install

script:
  - echo "Building the project..."

after_success:
  - curl -X POST https://api.render.com/deploy/srv-d0m0foogjchc739dmgog?key=bjeD6_iH2OM