language: node_js
node_js:
  - "22"

services:
  - docker

before_install:
  - npm install -g @angular/cli

install:
  - npm install

script:
  - ng build --prod
  - docker build -t snapface-angular-app .

after_success:
  - curl -X POST https://api.render.com/deploy/srv-d0m0foogjchc739dmgog?key=bjeD6_iH2OM