name: Deploy Angular App with Docker to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build --prod

    # Vu que Render construitr l'image Docker, on ne doit pas construire l'image ici
    #- name: Build Docker image
    # run: docker build -t snapface-angular-app .

    - name: Trigger Render deployment via webhook
      run: |
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
